### ISSUE TITLE
need to remove this space

### ISSUE THREAD

**Issue by mutageneral** [levonium/learning-markdown#12]
With the space
![image](https://user-images.githubusercontent.com/62779748/116891576-dfd02300-abfc-11eb-908d-079c24735346.png)
Without
![image](https://user-images.githubusercontent.com/62779748/116891656-f6767a00-abfc-11eb-989f-f7427ff3995c.png)
It's in the Formatting section

**Comment by levonium** [comment]
Removed, thanks @mutageneral
